image: docker:latest

services:
    - docker:dind

variables:
    BMS_IMAGE_TAG: $CI_REGISTRY_IMAGE/bms:$CI_COMMIT_REF_NAME
    JETH_IMAGE_TAG: $CI_REGISTRY_IMAGE/jeth:$CI_COMMIT_REF_NAME

before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
    stage: build
    script:
        - docker build -t $BMS_IMAGE_TAG ./bms/
        - docker push $BMS_IMAGE_TAG
        - docker build -t $JETH_IMAGE_TAG ./jeth/
        - docker push $JETH_IMAGE_TAG
