# Generated by Django 2.0.5 on 2018-05-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blockchain',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
