# Generated by Django 2.0.5 on 2018-05-20 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blockchain', '0002_auto_20180520_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
            ],
            options={
                'verbose_name': 'блокчейн',
                'verbose_name_plural': 'блокчейны',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('source', models.TextField(verbose_name='исходный код')),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.Blockchain', verbose_name='блокчейн')),
            ],
            options={
                'verbose_name': 'контракт',
                'verbose_name_plural': 'контракты',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('queue_name', models.CharField(max_length=100, verbose_name='название очереди')),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.Blockchain', verbose_name='блокчейн')),
            ],
            options={
                'verbose_name': 'нода',
                'verbose_name_plural': 'ноды',
            },
        ),
    ]
