# Generated by Django 2.0.5 on 2018-05-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_blockchain_contract_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='enode',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='enode'),
        ),
        migrations.AddField(
            model_name='blockchain',
            name='genesis_block',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Genesis block'),
        ),
        migrations.AddField(
            model_name='blockchain',
            name='network_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='network id'),
        ),
        migrations.AddField(
            model_name='blockchain',
            name='port',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='порт'),
        ),
    ]
