# Generated by Django 2.0.5 on 2018-05-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0004_auto_20180530_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='process_pid',
            field=models.IntegerField(default=0, verbose_name='pid процесса geth'),
        ),
        migrations.AddField(
            model_name='node',
            name='process_pid',
            field=models.IntegerField(default=0, verbose_name='pid процесса geth'),
        ),
    ]
