# Generated by Django 2.0.5 on 2018-05-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0005_auto_20180531_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='port',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='порт'),
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='process_pid',
            field=models.IntegerField(blank=True, null=True, verbose_name='pid процесса geth'),
        ),
    ]
